services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test-db
      MYSQL_USER: cats4ever
      MYSQL_PASSWORD: cats4life
      MARIADB_INITDB_ARGS: "--collation=utf8mb4_general_ci --character-set-server=utf8mb4"
    ports:
      - "3306:3306"
    volumes:
      - ./recensement.sql:/docker-entrypoint-initdb.d/recensement_init.sql
      - ./book.sql:/docker-entrypoint-initdb.d/book_init.sql
